# Generated by Django 3.1.4 on 2020-12-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='complete',
            new_name='finished',
        ),
    ]
