# Generated by Django 3.1.5 on 2021-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_products_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
