# Generated by Django 2.0.7 on 2021-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20210111_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.TextField(default=0),
        ),
    ]
