# Generated by Django 3.1.5 on 2021-01-29 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen', '0006_auto_20210116_1857'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductInKitchen',
        ),
    ]
