# Generated by Django 3.1.3 on 2021-01-20 18:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserRating',
        ),
    ]
