# Generated by Django 3.1.5 on 2021-01-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_userrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='priority',
        ),
    ]
