# Generated by Django 3.1.3 on 2021-01-22 15:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='ratings', through='recipes.UserRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
