# Generated by Django 3.1.3 on 2021-01-22 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_recipe_rated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated_recipes', through='recipes.UserRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
