# Generated by Django 3.1.5 on 2021-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_tobuy_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobuy',
            name='amount',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
